{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rr-bsord.serviceAccountName" . }}
  labels:
{{ include "rr-bsord.labels" . | nindent 4 }}
{{- end -}}
