apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 587
      protocol: TCP
      name: smtp
  selector:
    {{- include "postfix.selectorLabels" . | nindent 4 }}
