{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rcvr-smtp.serviceAccountName" . }}
  labels:
{{ include "rcvr-smtp.labels" . | nindent 4 }}
{{- end -}}
